// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateAlbumParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum, arg.ID, arg.Name)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateArtistParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.ID, arg.Name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateGenreParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre, arg.ID, arg.Name)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrCreateAlbum = `-- name: FindOrCreateAlbum :one
INSERT INTO albums (id, name)
VALUES ($1, $2)
ON CONFLICT (LOWER(name)) DO UPDATE
SET name = albums.name
RETURNING id, name, created_at, updated_at
`

type FindOrCreateAlbumParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) FindOrCreateAlbum(ctx context.Context, arg FindOrCreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, findOrCreateAlbum, arg.ID, arg.Name)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrCreateArtist = `-- name: FindOrCreateArtist :one
INSERT INTO artists (id, name)
VALUES ($1, $2)
ON CONFLICT (LOWER(name)) DO UPDATE
SET name = artists.name
RETURNING id, name, created_at, updated_at
`

type FindOrCreateArtistParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) FindOrCreateArtist(ctx context.Context, arg FindOrCreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, findOrCreateArtist, arg.ID, arg.Name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, name, created_at, updated_at
FROM albums
WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id uuid.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumByName = `-- name: GetAlbumByName :one
SELECT id, name, created_at, updated_at
FROM albums
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) GetAlbumByName(ctx context.Context, lower string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByName, lower)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, created_at, updated_at
FROM artists
WHERE id = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, created_at, updated_at
FROM artists
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) GetArtistByName(ctx context.Context, lower string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, lower)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenreByID = `-- name: GetGenreByID :one
SELECT id, name, created_at, updated_at
FROM genres
WHERE id = $1
`

func (q *Queries) GetGenreByID(ctx context.Context, id uuid.UUID) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByID, id)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenreByName = `-- name: GetGenreByName :one
SELECT id, name, created_at, updated_at
FROM genres
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) GetGenreByName(ctx context.Context, lower string) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByName, lower)
	var i Genre
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGenres = `-- name: ListGenres :many
SELECT id, name, created_at, updated_at
FROM genres
ORDER BY name
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
