// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFavorite = `-- name: AddFavorite :one
INSERT INTO favorites (user_id, track_id)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1
    FROM tracks
    WHERE id = $2
      AND deleted_at IS NULL
)
RETURNING user_id, track_id, created_at
`

type AddFavoriteParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, addFavorite, arg.UserID, arg.TrackID)
	var i Favorite
	err := row.Scan(&i.UserID, &i.TrackID, &i.CreatedAt)
	return i, err
}

const countFavoritesByUserID = `-- name: CountFavoritesByUserID :one
SELECT COUNT(*)
FROM favorites
WHERE user_id = $1
`

func (q *Queries) CountFavoritesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const favoriteExists = `-- name: FavoriteExists :one
SELECT EXISTS (
    SELECT 1
    FROM favorites
    WHERE user_id = $1
      AND track_id = $2
)
`

type FavoriteExistsParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) FavoriteExists(ctx context.Context, arg FavoriteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, favoriteExists, arg.UserID, arg.TrackID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoritesByUserID = `-- name: ListFavoritesByUserID :many
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at,
       f.created_at AS favorited_at
FROM favorites f
JOIN tracks t ON t.id = f.track_id
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
WHERE f.user_id = $1
  AND t.deleted_at IS NULL
ORDER BY f.created_at DESC, t.id
`

type ListFavoritesByUserIDRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	FavoritedAt     time.Time
}

func (q *Queries) ListFavoritesByUserID(ctx context.Context, userID uuid.UUID) ([]ListFavoritesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFavoritesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesByUserIDRow{}
	for rows.Next() {
		var i ListFavoritesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumName,
			&i.GenreID,
			&i.GenreName,
			&i.DurationSeconds,
			&i.FileUrl,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FavoritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :one
DELETE FROM favorites
WHERE user_id = $1
  AND track_id = $2
RETURNING user_id, track_id
`

type RemoveFavoriteParams struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

type RemoveFavoriteRow struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (RemoveFavoriteRow, error) {
	row := q.db.QueryRow(ctx, removeFavorite, arg.UserID, arg.TrackID)
	var i RemoveFavoriteRow
	err := row.Scan(&i.UserID, &i.TrackID)
	return i, err
}
