// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createListeningHistory = `-- name: CreateListeningHistory :one
INSERT INTO listening_history (id, user_id, track_id)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1
    FROM tracks
    WHERE id = $3
      AND deleted_at IS NULL
)
RETURNING id, user_id, track_id, listened_at
`

type CreateListeningHistoryParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	TrackID uuid.UUID
}

func (q *Queries) CreateListeningHistory(ctx context.Context, arg CreateListeningHistoryParams) (ListeningHistory, error) {
	row := q.db.QueryRow(ctx, createListeningHistory, arg.ID, arg.UserID, arg.TrackID)
	var i ListeningHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ListenedAt,
	)
	return i, err
}

const listListeningHistoryByUserID = `-- name: ListListeningHistoryByUserID :many
SELECT h.id,
       h.user_id,
       t.id AS track_id,
       t.title,
       ar.name AS artist_name,
       h.listened_at
FROM listening_history h
JOIN tracks t ON t.id = h.track_id
JOIN artists ar ON ar.id = t.artist_id
WHERE h.user_id = $1
  AND t.deleted_at IS NULL
ORDER BY h.listened_at DESC, h.id
LIMIT $3 OFFSET $2
`

type ListListeningHistoryByUserIDParams struct {
	UserID uuid.UUID
	Offset int32
	Limit  int32
}

type ListListeningHistoryByUserIDRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TrackID    uuid.UUID
	Title      string
	ArtistName string
	ListenedAt time.Time
}

func (q *Queries) ListListeningHistoryByUserID(ctx context.Context, arg ListListeningHistoryByUserIDParams) ([]ListListeningHistoryByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listListeningHistoryByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListeningHistoryByUserIDRow{}
	for rows.Next() {
		var i ListListeningHistoryByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.Title,
			&i.ArtistName,
			&i.ListenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
