// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SubscriptionType string

const (
	SubscriptionTypeFREE    SubscriptionType = "FREE"
	SubscriptionTypePREMIUM SubscriptionType = "PREMIUM"
)

func (e *SubscriptionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionType(s)
	case string:
		*e = SubscriptionType(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionType: %T", src)
	}
	return nil
}

type NullSubscriptionType struct {
	SubscriptionType SubscriptionType
	Valid            bool // Valid is true if SubscriptionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionType) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionType), nil
}

type UserRole string

const (
	UserRoleUSER  UserRole = "USER"
	UserRoleADMIN UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Album struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Artist struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Favorite struct {
	UserID    uuid.UUID
	TrackID   uuid.UUID
	CreatedAt time.Time
}

type Genre struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ListeningHistory struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TrackID    uuid.UUID
	ListenedAt time.Time
}

type Playlist struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlaylistTrack struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
	AddedAt    time.Time
}

type Track struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	AlbumID         uuid.UUID
	GenreID         uuid.UUID
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID               uuid.UUID
	Email            string
	Username         string
	PasswordHash     string
	Salt             string
	Role             UserRole
	SubscriptionType SubscriptionType
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
