// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTrackToPlaylist = `-- name: AddTrackToPlaylist :one
INSERT INTO playlist_tracks (playlist_id, track_id)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1
    FROM playlists
    WHERE id = $1
      AND user_id = $3
)
  AND EXISTS (
    SELECT 1
    FROM tracks
    WHERE id = $2
      AND deleted_at IS NULL
)
RETURNING playlist_id, track_id, added_at
`

type AddTrackToPlaylistParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) (PlaylistTrack, error) {
	row := q.db.QueryRow(ctx, addTrackToPlaylist, arg.PlaylistID, arg.TrackID, arg.UserID)
	var i PlaylistTrack
	err := row.Scan(&i.PlaylistID, &i.TrackID, &i.AddedAt)
	return i, err
}

const countPlaylistsByUserID = `-- name: CountPlaylistsByUserID :one
SELECT COUNT(*)
FROM playlists
WHERE user_id = $1
`

func (q *Queries) CountPlaylistsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (id, user_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, description, created_at, updated_at
`

type CreatePlaylistParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :one
DELETE FROM playlists
WHERE id = $1
  AND user_id = $2
RETURNING id
`

type DeletePlaylistParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deletePlaylist, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPlaylistByIDForUser = `-- name: GetPlaylistByIDForUser :one
SELECT id, user_id, name, description, created_at, updated_at
FROM playlists
WHERE id = $1
  AND user_id = $2
`

type GetPlaylistByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPlaylistByIDForUser(ctx context.Context, arg GetPlaylistByIDForUserParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByIDForUser, arg.ID, arg.UserID)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at,
       pt.added_at
FROM playlist_tracks pt
JOIN playlists p ON p.id = pt.playlist_id
JOIN tracks t ON t.id = pt.track_id
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
WHERE pt.playlist_id = $1
  AND p.user_id = $2
  AND t.deleted_at IS NULL
ORDER BY pt.added_at DESC, t.id
`

type ListPlaylistTracksParams struct {
	PlaylistID uuid.UUID
	UserID     uuid.UUID
}

type ListPlaylistTracksRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AddedAt         time.Time
}

func (q *Queries) ListPlaylistTracks(ctx context.Context, arg ListPlaylistTracksParams) ([]ListPlaylistTracksRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, arg.PlaylistID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistTracksRow{}
	for rows.Next() {
		var i ListPlaylistTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumName,
			&i.GenreID,
			&i.GenreName,
			&i.DurationSeconds,
			&i.FileUrl,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByUserID = `-- name: ListPlaylistsByUserID :many
SELECT id, user_id, name, description, created_at, updated_at
FROM playlists
WHERE user_id = $1
ORDER BY created_at DESC, id
`

func (q *Queries) ListPlaylistsByUserID(ctx context.Context, userID uuid.UUID) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackFromPlaylist = `-- name: RemoveTrackFromPlaylist :one
DELETE FROM playlist_tracks
WHERE playlist_id = $1
  AND track_id = $2
  AND EXISTS (
      SELECT 1
      FROM playlists
      WHERE id = $1
        AND user_id = $3
  )
RETURNING playlist_id, track_id
`

type RemoveTrackFromPlaylistParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
	UserID     uuid.UUID
}

type RemoveTrackFromPlaylistRow struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

func (q *Queries) RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) (RemoveTrackFromPlaylistRow, error) {
	row := q.db.QueryRow(ctx, removeTrackFromPlaylist, arg.PlaylistID, arg.TrackID, arg.UserID)
	var i RemoveTrackFromPlaylistRow
	err := row.Scan(&i.PlaylistID, &i.TrackID)
	return i, err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET name = $3,
    description = $4,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, description, created_at, updated_at
`

type UpdatePlaylistParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
