// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTrack = `-- name: CreateTrack :one
WITH inserted AS (
    INSERT INTO tracks (id, title, artist_id, album_id, genre_id, duration_seconds, file_url)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, title, artist_id, album_id, genre_id, duration_seconds, file_url, deleted_at, created_at, updated_at
)
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at
FROM inserted t
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
`

type CreateTrackParams struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	AlbumID         uuid.UUID
	GenreID         uuid.UUID
	DurationSeconds int32
	FileUrl         string
}

type CreateTrackRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (CreateTrackRow, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.ID,
		arg.Title,
		arg.ArtistID,
		arg.AlbumID,
		arg.GenreID,
		arg.DurationSeconds,
		arg.FileUrl,
	)
	var i CreateTrackRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ArtistName,
		&i.AlbumID,
		&i.AlbumName,
		&i.GenreID,
		&i.GenreName,
		&i.DurationSeconds,
		&i.FileUrl,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at
FROM tracks t
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
WHERE t.id = $1
  AND t.deleted_at IS NULL
`

type GetTrackByIDRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetTrackByID(ctx context.Context, id uuid.UUID) (GetTrackByIDRow, error) {
	row := q.db.QueryRow(ctx, getTrackByID, id)
	var i GetTrackByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ArtistName,
		&i.AlbumID,
		&i.AlbumName,
		&i.GenreID,
		&i.GenreName,
		&i.DurationSeconds,
		&i.FileUrl,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTracks = `-- name: ListTracks :many
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at
FROM tracks t
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
WHERE t.deleted_at IS NULL
ORDER BY t.created_at DESC, t.id
LIMIT $2 OFFSET $1
`

type ListTracksParams struct {
	Offset int32
	Limit  int32
}

type ListTracksRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracksRow{}
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumName,
			&i.GenreID,
			&i.GenreName,
			&i.DurationSeconds,
			&i.FileUrl,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracks = `-- name: SearchTracks :many
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at
FROM tracks t
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
WHERE t.deleted_at IS NULL
  AND (
      t.title ILIKE '%' || $1::text || '%'
      OR ar.name ILIKE '%' || $1::text || '%'
      OR al.name ILIKE '%' || $1::text || '%'
      OR g.name ILIKE '%' || $1::text || '%'
  )
ORDER BY t.created_at DESC, t.id
LIMIT $3 OFFSET $2
`

type SearchTracksParams struct {
	Query  string
	Offset int32
	Limit  int32
}

type SearchTracksRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) SearchTracks(ctx context.Context, arg SearchTracksParams) ([]SearchTracksRow, error) {
	rows, err := q.db.Query(ctx, searchTracks, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTracksRow{}
	for rows.Next() {
		var i SearchTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumName,
			&i.GenreID,
			&i.GenreName,
			&i.DurationSeconds,
			&i.FileUrl,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrack = `-- name: SoftDeleteTrack :one
UPDATE tracks
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE tracks.id = $1
  AND tracks.deleted_at IS NULL
RETURNING tracks.id
`

func (q *Queries) SoftDeleteTrack(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteTrack, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const trackExists = `-- name: TrackExists :one
SELECT EXISTS (
    SELECT 1
    FROM tracks
    WHERE id = $1
      AND deleted_at IS NULL
)
`

func (q *Queries) TrackExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, trackExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTrack = `-- name: UpdateTrack :one
WITH updated AS (
    UPDATE tracks
    SET title = $2,
        artist_id = $3,
        album_id = $4,
        genre_id = $5,
        duration_seconds = $6,
        file_url = $7,
        updated_at = NOW()
    WHERE tracks.id = $1
      AND tracks.deleted_at IS NULL
    RETURNING tracks.id, tracks.title, tracks.artist_id, tracks.album_id, tracks.genre_id, tracks.duration_seconds, tracks.file_url, tracks.deleted_at, tracks.created_at, tracks.updated_at
)
SELECT t.id,
       t.title,
       t.artist_id,
       ar.name AS artist_name,
       t.album_id,
       al.name AS album_name,
       t.genre_id,
       g.name AS genre_name,
       t.duration_seconds,
       t.file_url,
       t.deleted_at,
       t.created_at,
       t.updated_at
FROM updated t
JOIN artists ar ON ar.id = t.artist_id
JOIN albums al ON al.id = t.album_id
JOIN genres g ON g.id = t.genre_id
`

type UpdateTrackParams struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	AlbumID         uuid.UUID
	GenreID         uuid.UUID
	DurationSeconds int32
	FileUrl         string
}

type UpdateTrackRow struct {
	ID              uuid.UUID
	Title           string
	ArtistID        uuid.UUID
	ArtistName      string
	AlbumID         uuid.UUID
	AlbumName       string
	GenreID         uuid.UUID
	GenreName       string
	DurationSeconds int32
	FileUrl         string
	DeletedAt       *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (UpdateTrackRow, error) {
	row := q.db.QueryRow(ctx, updateTrack,
		arg.ID,
		arg.Title,
		arg.ArtistID,
		arg.AlbumID,
		arg.GenreID,
		arg.DurationSeconds,
		arg.FileUrl,
	)
	var i UpdateTrackRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ArtistName,
		&i.AlbumID,
		&i.AlbumName,
		&i.GenreID,
		&i.GenreName,
		&i.DurationSeconds,
		&i.FileUrl,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
